version: "3"
services:
  latteart-builder:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
      args:
        - HTTP_PROXY=$HTTP_PROXY
        - http_proxy=$http_proxy
        - HTTPS_PROXY=$HTTPS_PROXY
        - https_proxy=$https_proxy
        - FTP_PROXY=$FTP_PROXY
        - ftp_proxy=$ftp_proxy
        - NO_PROXY=$NO_PROXY
        - no_proxy=$no_proxy
    container_name: latteart-builder
    volumes:
      - ./data:/usr/src/app/data
