name: Manual Packaging

on:
  workflow_dispatch:

jobs:
  package:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.15.3]
        os: [win, mac]

    steps:
      - name: Checkout 'LatteArt' Repository
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          path: latteart

      - name: Checkout 'LatteArt Capture CL' Repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/latteart-capture-cl
          ref: ${{ github.ref }}
          path: latteart-capture-cl

      - name: Checkout 'LatteArt Repository' Repository
        uses: actions/checkout@v2
        with:
          repository: ${{ github.repository_owner }}/latteart-repository
          ref: ${{ github.ref }}
          path: latteart-repository

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies of 'LatteArt'
        uses: actions/cache@v3
        id: cache-latteart-dependencies
        env:
          cache-name: cache-node-modules
        with:
          path: "latteart/**/node_modules"
          key: ${{ runner.os }}-package-${{ matrix.node-version }}-${{ env.cache-name }}-${{ hashFiles('latteart/**/yarn.lock') }}

      - name: Install dependencies of 'LatteArt'
        if: ${{ steps.cache-latteart-dependencies.outputs.cache-hit != 'true' }}
        run: |
          cd latteart
          yarn install
          cd ..

      - name: Package 'LatteArt'
        run: |
          cd latteart
          yarn package:${{ matrix.os }}
          mkdir -p latteart
          cp -rp dist/latteart/* latteart
          cd ..

      - name: Cache dependencies of 'LatteArt Repository'
        uses: actions/cache@v3
        id: cache-repository-dependencies
        env:
          cache-name: cache-node-modules
        with:
          path: "latteart-repository/**/node_modules"
          key: ${{ runner.os }}-package-${{ matrix.node-version }}-${{ env.cache-name }}-${{ hashFiles('latteart-repository/**/yarn.lock') }}

      - name: Install dependencies of 'LatteArt Repository'
        if: ${{ steps.cache-repository-dependencies.outputs.cache-hit != 'true' }}
        run: |
          cd latteart-repository
          yarn install
          cd ..

      - name: Package 'LatteArt Repository'
        run: |
          cd latteart-repository
          yarn typescript-json-validator src/lib/settings/Settings.ts
          yarn typescript-json-validator src/lib/settings/DeviceSettings.ts
          yarn package:${{ matrix.os }}
          mkdir -p latteart
          cp -rp dist/latteart-repository latteart
          cd ..

      - name: Cache dependencies of 'LatteArt Capture CL'
        uses: actions/cache@v3
        id: cache-capture-cl-dependencies
        env:
          cache-name: cache-node-modules
        with:
          path: "latteart-capture-cl/**/node_modules"
          key: ${{ runner.os }}-package-${{ matrix.node-version }}-${{ env.cache-name }}-${{ hashFiles('latteart-capture-cl/**/yarn.lock') }}

      - name: Install dependencies of 'LatteArt Capture CL'
        if: ${{ steps.cache-capture-cl-dependencies.outputs.cache-hit != 'true' }}
        run: |
          cd latteart-capture-cl
          yarn install
          cd ..

      - name: Package 'LatteArt Capture CL'
        run: |
          cd latteart-capture-cl
          yarn package:${{ matrix.os }}
          mkdir -p latteart
          cp -rp dist/latteart-capture-cl latteart
          cd ..

      - name: Make Artifact
        run: |
          mkdir artifact
          cp -r latteart/latteart/* artifact
          cp -r latteart-capture-cl/latteart/* artifact
          cp -r latteart-repository/latteart/* artifact

      - name: Build Artifact Name
        id: build_artifact_name
        run: |
          ARTIFACT_NAME=$(echo ${{ github.ref_name }} | sed "s/\//-/g")
          echo ::set-output name=artifact_name::$ARTIFACT_NAME

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: latteart-${{ steps.build_artifact_name.outputs.artifact_name }}-${{ matrix.os }}
          path: artifact
