name: Type Check latteart-gui

on:
  push:
    branches-ignore:
      - "release/**"
    tags-ignore:
      - "v*"
    paths:
      - packages/latteart-gui/**
      - .github/workflows/typecheck_gui.yml

jobs:
  typecheck_gui:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [22.13.1]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ matrix.node-version }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: ${{ steps.cache-dependencies.outputs.cache-hit != 'true' }}
        run: |
          npm install

      - name: Run Type Check
        run: |
          npm run build -w latteart-client
          npm run type-check -w latteart-gui
