name: UT latteart-capture-cl

on:
  push:
    paths:
      - packages/latteart-capture-cl/**
      - .github/workflows/ut_capture_cl.yml

jobs:
  ut:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.13.2]

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache dependencies
        uses: actions/cache@v3
        id: cache-dependencies
        env:
          cache-name: cache-node-modules
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-build-${{ matrix.node-version }}-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}

      - name: Install dependencies
        if: ${{ steps.cache-dependencies.outputs.cache-hit != 'true' }}
        run: |
          npm install

      - name: Run Tests
        run: |
          npm run build -w latteart-client
          npm run test -w latteart-capture-cl
